const bcrypt = require("bcryptjs");

const data = {
  users: [
    {
      firstName: "Basir",
      lastName: "Admin",
      email: "admin@yopmail.com",
      dateOfBirth: "1999-10-06",
      phoneNo: "7798330187",
      password: bcrypt.hashSync("123456"),
      role: "Admin",
      hasAcceptedTerms: 1,
    },
    {
      firstName: "John",
      lastName: "Aroon",
      email: "john.aroon@yopmail.com",
      dateOfBirth: "1999-10-06",
      phoneNo: "7798330189",
      password: bcrypt.hashSync("123456"),
      role: "Customer",
      hasAcceptedTerms: 1,
    },
  ],
  products: [
    {
      // _id: '1',
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      // _id: '2',
      name: "Adidas Fit Shirt",
      slug: "adidas-fit-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: '3',
      name: "Nike Slim Pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      // _id: '4',
      name: "Adidas Fit Pant",
      slug: "adidas-fit-pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
module.exports = data;
