const {
  MAIL_HOST,
  MAIL_PORT,
  MAIL_DRIVER,
  MAIL_FROM_ADDRESS,
  MAIL_FROM_NAME,
  MAIL_ENCRYPTION,
  MAIL_USERNAME,
  MAIL_PASSWORD,
  EMAIL_TEMPLATE_PATH,
} = process.env;

module.exports = {
  MAIL_HOST,
  MAIL_PORT,
  MAIL_DRIVER,
  MAIL_FROM_ADDRESS,
  MAIL_FROM_NAME,
  MAIL_ENCRYPTION,
  MAIL_USERNAME,
  MAIL_PASSWORD,
  EMAIL_TEMPLATE_PATH,
};
